# attempt to use API directly?

In [2]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests

import os
import warnings
from urllib.parse import urlencode, urljoin
from urllib.request import urlopen

from cartopy import crs as ccrs, feature as cfeature
import netCDF4
from netCDF4 import Dataset
from datetime import datetime as dt

## using pointers from this page: https://eccc-msc.github.io/open-data/msc-geomet/ogc_api_en/ and https://pavics-sdi.readthedocs.io/en/latest/notebooks/eccc-geoapi-xclim.html, and collection documentation from https://api.weather.gc.ca/collections

## Collection: climate-daily

In [11]:
# Compose the request
host = "https://api.weather.gc.ca/"
api = urljoin(host, "collections/climate-daily/items/")
query = {
    "datetime": "2026-10-05/..", # all items from 2026-10-05 onward
    #"datetime": "1840-03-01 00:00:00/2021-06-02 00:00:00",
    "bbox": "-123.25,49,-123.0,49.25",# minX, minY, maxX, maxY
    #"STN_ID": "10761",
    "sortby": "LOCAL_DATE",
    "f": "csv"
}
url = f"{api}?{urlencode(query)}"


# Use geopandas to convert the json output to a GeoDataFrame.
with urlopen(url=str(url)) as req:
    df = pd.read_csv(req)
df.sort_index().head(20)

,x,y,STATION_NAME,CLIMATE_IDENTIFIER,ID,LOCAL_DATE,PROVINCE_CODE,LOCAL_YEAR,LOCAL_MONTH,LOCAL_DAY,...,DIRECTION_MAX_GUST_FLAG,SPEED_MAX_GUST,SPEED_MAX_GUST_FLAG,COOLING_DEGREE_DAYS,COOLING_DEGREE_DAYS_FLAG,HEATING_DEGREE_DAYS,HEATING_DEGREE_DAYS_FLAG,MIN_REL_HUMIDITY,MIN_REL_HUMIDITY_FLAG,STN_ID
0,-123.100104,49.233513,VANCOUVER HILLCREST,1108433,1108433.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48328
1,-123.078100,49.181900,RICHMOND OPERATIONS CENTRE,1105210,1105210.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48448
2,-123.002246,49.125848,DELTA BURNS BOG,1102415,1102415.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49088
3,-123.133344,49.003911,TSAWWASSEN FERRY AUTO,1108291,1108291.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50228
4,-123.187236,49.182500,VANCOUVER SEA ISLAND CCG,1108380,1108380.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51357
5,-123.183889,49.194722,VANCOUVER INTL A,1108395,1108395.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51442
6,-123.183889,49.194722,VANCOUVER INT'L HWOS,1108425,1108425.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52218
7,-123.008333,49.073333,VANCOUVER BOUNDARY BAY,1100909,1100909.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55458
8,-123.000000,49.216667,BURNABY METROTOWN,110A1ND,110A1ND.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,671
9,-123.000000,49.250000,BURNABY BC INST TECHNOL,1101142,1101142.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,722
10,-123.016667,49.216667,BURNABY SUNCREST,1101160,1101160.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,732
11,-123.066667,49.033333,DELTA BEACH GROVE,1102412,1102412.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,759
12,-123.066667,49.083333,DELTA LADNER EAST,1102416,1102416.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,760
13,-123.083333,49.066667,DELTA LADNER SOUTH,1102417,1102417.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,761
14,-123.083333,49.000000,DELTA PEBBLE HILL,1102420,1102420.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,763
15,-123.100000,49.016667,DELTA TSAWWASSEN,1102424,1102424.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,765
16,-123.093333,49.010944,DELTA TSAWWASSEN BEACH,1102425,1102425.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,766
17,-123.066667,49.083333,LADNER,1104468,1104468.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,789
18,-123.016667,49.083333,LADNER,1104470,1104470.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,790
19,-123.050000,49.083333,LADNER BCHPA,1104473,1104473.2026.10.5,2026-10-05 00:00:00,BC,2026,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,791

## Collection: climate-normals

In [15]:
# Compose the request
host = "https://api.weather.gc.ca/"
api = urljoin(host, "collections/climate-normals/items/")
query = {
    #"DATE_CALCULATED" : "2026-10-05",
    #"datetime": "2026-10-05", # all items from 2026-10-05 onward
    #"datetime": "1840-03-01 00:00:00/2021-06-02 00:00:00",
    #"bbox": "-123.25,49,-123.0,49.25",# minX, minY, maxX, maxY
    "STN_ID": "51442", # Vancouver Intl A
    "properties": "VALUE",
    #"sortby": "LOCAL_DATE",
    "f": "csv"
}
url = f"{api}?{urlencode(query)}"


# Use pandas to convert the csv output to a data frame.
with urlopen(url=str(url)) as req:
    df = pd.read_csv(req)
df.sort_index().head()

HTTPError: HTTP Error 400: BAD REQUEST

## Collection: climate-stations

In [19]:
# Compose the request
host = "https://api.weather.gc.ca/"
api = urljoin(host, "collections/climate-stations/items/")
query = {"ENG_PROV_NAME": "BRITISH-COLUMBIA",
        "f":"csv"}
url = f"{api}?{urlencode(query)}"
print(url)

# Send the request to the server
resp = requests.get(url)
resp

#url = f"{api}?{urlencode(query)}"


# Use pandas to convert the csv output to a data frame.
with urlopen(url=str(url)) as req:
    df = pd.read_csv(req)
df.sort_index().head(20)

https://api.weather.gc.ca/collections/climate-stations/items/?ENG_PROV_NAME=BRITISH-COLUMBIA&f=csv

,x,y,STN_ID,STATION_NAME,PROV_STATE_TERR_CODE,ENG_PROV_NAME,FRE_PROV_NAME,COUNTRY,LATITUDE,LONGITUDE,...,LAST_DATE,HLY_FIRST_DATE,HLY_LAST_DATE,DLY_FIRST_DATE,DLY_LAST_DATE,MLY_FIRST_DATE,MLY_LAST_DATE,HAS_MONTHLY_SUMMARY,HAS_NORMALS_DATA,HAS_HOURLY_DATA
0,-123.700000,48.916667,2,CHEMAINUS BARE POINT,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,485500000,-1234200000,...,1979-12-31 00:00:00,NaN,NaN,1979-11-01 00:00:00,1979-12-31 00:00:00,1979-01-01 00:00:00,1979-12-01 00:00:00,Y,N,N
1,-123.350000,48.883333,3,GALIANO SOUTH 2,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,485300000,-1232100000,...,1984-12-01 00:00:00,NaN,NaN,1979-05-01 00:00:00,1984-01-31 00:00:00,1979-01-01 00:00:00,1984-12-01 00:00:00,Y,N,N
2,-123.316667,48.866667,4,GALIANO SOUTH,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,485200000,-1231900000,...,1978-12-31 00:00:00,NaN,NaN,1977-07-01 00:00:00,1978-12-31 00:00:00,1977-01-01 00:00:00,1978-12-01 00:00:00,Y,N,N
3,-123.416667,48.550000,5,SAANICH OLDFIELD NORTH,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483300000,-1232500000,...,1967-12-01 00:00:00,NaN,NaN,1965-12-01 00:00:00,1967-03-31 00:00:00,1966-01-01 00:00:00,1967-12-01 00:00:00,Y,N,N
4,-123.266944,48.455000,6,VICTORIA PHYLLIS STREET,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482718000,-1231601000,...,2001-08-31 00:00:00,NaN,NaN,1973-06-01 00:00:00,2001-08-31 00:00:00,1973-01-01 00:00:00,2001-08-01 00:00:00,Y,N,N
5,-123.433333,48.450000,7,VICTORIA PORTAGE INLET,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482700000,-1232600000,...,1983-12-01 00:00:00,NaN,NaN,1976-05-01 00:00:00,1983-05-31 00:00:00,1976-01-01 00:00:00,1983-12-01 00:00:00,Y,N,N
6,-123.300000,48.433333,8,VICTORIA WILLOWS PARK,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482600000,-1231800000,...,1979-12-01 00:00:00,NaN,NaN,1970-04-01 00:00:00,1979-01-31 00:00:00,1970-01-01 00:00:00,1979-12-01 00:00:00,Y,N,N
7,-123.383333,48.433333,9,VICTORIA WEST,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482600000,-1232300000,...,1968-12-01 00:00:00,NaN,NaN,1967-10-01 00:00:00,1968-07-31 00:00:00,1967-01-01 00:00:00,1968-12-01 00:00:00,Y,N,N
8,-123.366667,48.450000,10,VICTORIA SHORT STREET,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482700000,-1232200000,...,1973-12-01 00:00:00,NaN,NaN,1961-11-01 00:00:00,1973-08-31 00:00:00,1961-01-01 00:00:00,1973-12-01 00:00:00,Y,N,N
9,-123.333333,48.466667,11,VICTORIA SHELBOURNE,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482800000,-1232000000,...,1991-11-01 00:00:00,NaN,NaN,1964-05-01 00:00:00,1991-10-31 00:00:00,1964-01-01 00:00:00,1991-11-01 00:00:00,Y,N,N
10,-123.433333,48.516667,12,VICTORIA PROSPECT LAKE,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483100000,-1232600000,...,1986-12-01 00:00:00,NaN,NaN,1973-11-01 00:00:00,1986-11-30 00:00:00,1973-01-01 00:00:00,1986-12-01 00:00:00,Y,N,N
11,-123.350000,48.433333,13,VICTORIA PRINCESS AVE,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482600000,-1232100000,...,1991-12-01 00:00:00,NaN,NaN,1973-11-01 00:00:00,1991-11-30 00:00:00,1973-01-01 00:00:00,1991-12-01 00:00:00,Y,N,N
12,-123.283333,48.866667,14,ACTIVE PASS,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,485200000,-1231700000,...,1996-11-30 00:00:00,NaN,NaN,1984-07-01 00:00:00,1996-11-30 00:00:00,1984-01-01 00:00:00,1996-11-01 00:00:00,Y,N,N
13,-123.483333,48.400000,15,ALBERT HEAD,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482400000,-1232900000,...,1995-04-30 00:00:00,NaN,NaN,1971-06-01 00:00:00,1995-04-30 00:00:00,1971-01-01 00:00:00,1995-04-01 00:00:00,Y,N,N
14,-123.516667,48.583333,16,BAMBERTON OCEAN CEMENT,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483500000,-1233100000,...,1980-12-01 00:00:00,NaN,NaN,1961-02-01 00:00:00,1980-11-30 00:00:00,1961-01-01 00:00:00,1980-12-01 00:00:00,Y,N,N
15,-124.000000,48.500000,17,BEAR CREEK,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483000000,-1240000000,...,1971-12-01 00:00:00,NaN,NaN,1910-11-01 00:00:00,1971-08-31 00:00:00,1910-01-01 00:00:00,1971-12-01 00:00:00,Y,N,N
16,-123.350000,48.500000,18,BEAVER LAKE,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483000000,-1232100000,...,1952-12-01 00:00:00,NaN,NaN,1894-12-01 00:00:00,1952-06-30 00:00:00,1894-01-01 00:00:00,1952-12-01 00:00:00,Y,N,N
17,-123.633333,48.333333,19,BECHER BAY,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482000000,-1233800000,...,1966-12-01 00:00:00,NaN,NaN,1956-12-01 00:00:00,1966-04-30 00:00:00,1956-01-01 00:00:00,1966-12-01 00:00:00,Y,N,N
18,-123.466667,48.600000,20,BRENTWOOD BAY 2,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483600000,-1232800000,...,1997-05-31 00:00:00,NaN,NaN,1987-11-01 00:00:00,1997-05-31 00:00:00,1987-01-01 00:00:00,1997-05-01 00:00:00,Y,N,N
19,-123.450000,48.566667,21,BRENTWOOD CLARKE ROAD,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483400000,-1232700000,...,1980-12-01 00:00:00,NaN,NaN,1972-05-01 00:00:00,1980-03-31 00:00:00,1972-01-01 00:00:00,1980-12-01 00:00:00,Y,N,N

In [21]:
# which ones have climate normals?
df.query("HAS_NORMALS_DATA == 'Y'")

,x,y,STN_ID,STATION_NAME,PROV_STATE_TERR_CODE,ENG_PROV_NAME,FRE_PROV_NAME,COUNTRY,LATITUDE,LONGITUDE,...,LAST_DATE,HLY_FIRST_DATE,HLY_LAST_DATE,DLY_FIRST_DATE,DLY_LAST_DATE,MLY_FIRST_DATE,MLY_LAST_DATE,HAS_MONTHLY_SUMMARY,HAS_NORMALS_DATA,HAS_HOURLY_DATA
22,-123.392128,48.573342,24,CENTRAL SAANICH ISL VIEW,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483424030,-1232331660,...,2008-06-23 00:00:00,NaN,NaN,1970-03-01 00:00:00,2008-06-23 00:00:00,1970-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
35,-124.133333,48.824444,37,COWICHAN LAKE FORESTRY,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,484928000,-1240800000,...,2018-02-28 00:00:00,NaN,NaN,1949-04-01 00:00:00,2018-02-28 00:00:00,1949-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
66,-123.561389,48.374167,68,METCHOSIN,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,482227001,-1233341002,...,2026-09-29 00:00:00,NaN,NaN,1911-11-01 00:00:00,2026-09-29 00:00:00,1915-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
74,-123.718333,48.824167,76,NORTH COWICHAN,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,484927000,-1234306000,...,2026-10-01 00:00:00,NaN,NaN,1981-03-01 00:00:00,2026-10-01 00:00:00,1981-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
76,-123.427222,48.597500,78,SAANICHTON MT NEWTON,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,483551000,-1232538000,...,2026-10-03 00:00:00,NaN,NaN,1980-08-01 00:00:00,2026-10-03 00:00:00,1980-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,-127.170556,55.288611,450,SUSKWA VALLEY,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,551719000,-1271014000,...,2026-10-03 00:00:00,NaN,NaN,1982-10-01 00:00:00,2026-10-03 00:00:00,1982-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
454,-125.459722,54.446389,456,BABINE LAKE PINKUT CREEK,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,542647000,-1252735000,...,2012-02-28 00:00:00,NaN,NaN,1968-12-01 00:00:00,2012-02-28 00:00:00,1969-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
480,-129.029723,55.237500,482,NASS CAMP,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,551415000,-1290147004,...,2017-12-31 00:00:00,NaN,NaN,1973-09-01 00:00:00,2017-12-31 00:00:00,1973-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N
485,-127.182778,54.824722,487,SMITHERS A,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,544929000,-1271058000,...,2018-11-03 00:00:00,1953-01-01 00:00:00,2012-04-12 10:00:00,1942-06-01 00:00:00,2018-11-03 00:00:00,1942-01-01 00:00:00,2010-04-01 00:00:00,Y,Y,Y
494,-126.163056,54.815833,496,TOPLEY LANDING,BC,BRITISH COLUMBIA,COLOMBIE-BRITANNIQUE,CAN,544857000,-1260947000,...,2026-01-01 00:00:00,NaN,NaN,1962-06-01 00:00:00,2026-01-01 00:00:00,1962-01-01 00:00:00,2007-02-01 00:00:00,Y,Y,N

In [22]:
## maybe can try to above query for climate normals using this filtered list above

In [24]:
# Compose the request
host = "https://api.weather.gc.ca/"
api = urljoin(host, "collections/climate-normals/items/")
query = {
    #"DATE_CALCULATED" : "2026-10-05",
    #"datetime": "2026-10-05", # all items from 2026-10-05 onward
    #"datetime": "1840-03-01 00:00:00/2021-06-02 00:00:00",
    #"bbox": "-123.25,49,-123.0,49.25",# minX, minY, maxX, maxY
    "STN_ID": "24", # Vancouver Intl A
    #"properties": "VALUE",
    #"sortby": "LOCAL_DATE",
    "f": "csv"
}
url = f"{api}?{urlencode(query)}"


# Use pandas to convert the csv output to a data frame.
with urlopen(url=str(url)) as req:
    df = pd.read_csv(req)
df.sort_index().head()

,x,y,STATION_NAME,CLIMATE_IDENTIFIER,ID,PERIOD,CURRENT_FLAG,NORMAL_CODE,NORMAL_ID,PUBLICATION_CODE,...,YEAR_COUNT_NORMAL_PERIOD,TOTAL_OBS_COUNT,OCCURRENCE_COUNT,MAX_DURATION_MISSING_YEARS,PERCENT_OF_POSSIBLE_OBS,E_NORMAL_ELEMENT_NAME,F_NORMAL_ELEMENT_NAME,MONTH,VALUE,STN_ID
0,-123.392128,48.573342,CENTRAL SAANICH ISL VIEW,10114F6,24.82.6,NORM,Y,A,82,1,...,26,26,NaN,0,100.0,Mean month end snow depth cm,Épaisseur de la neige moyenne à la fin d'un mo...,6,0.0,24
1,-123.392128,48.573342,CENTRAL SAANICH ISL VIEW,10114F6,24.82.7,NORM,Y,A,82,1,...,26,26,NaN,0,100.0,Mean month end snow depth cm,Épaisseur de la neige moyenne à la fin d'un mo...,7,0.0,24
2,-123.392128,48.573342,CENTRAL SAANICH ISL VIEW,10114F6,24.82.8,NORM,Y,A,82,1,...,26,26,NaN,0,100.0,Mean month end snow depth cm,Épaisseur de la neige moyenne à la fin d'un mo...,8,0.0,24
3,-123.392128,48.573342,CENTRAL SAANICH ISL VIEW,10114F6,24.82.9,NORM,Y,A,82,1,...,26,26,NaN,0,100.0,Mean month end snow depth cm,Épaisseur de la neige moyenne à la fin d'un mo...,9,0.0,24
4,-123.392128,48.573342,CENTRAL SAANICH ISL VIEW,10114F6,24.82.10,NORM,Y,A,82,1,...,26,26,NaN,0,100.0,Mean month end snow depth cm,Épaisseur de la neige moyenne à la fin d'un mo...,10,0.0,24

# got it!